### ISSUE TITLE
what's neovim-remote for?

### ISSUE THREAD

**Issue by smartding** [voldikss/vim-floaterm#148]
I installed the floaterm plugin and ran lazygit inside it without any problem.
Then I see `:checkhealth` says I should install neovim-remote. What's it for?

**Comment by voldikss** [comment]
It's used to open a file in the nvim from within a terminal.

Suppose you don't have neovim-remote executable installed, after opening a builtin terminal you want to open a file from the terminal:

- If you just type `nvim example.txt`, you'll get a nested nvim in the terminal
- Otherwise you can just type `floaterm example.txt`, and the file will be opened in the only nvim without opening another nvim instance in the terminal.(But you must install neovim-remote to archive that if you are using nvim)

**Comment by voldikss** [comment]
> I installed the floaterm plugin and ran lazygit inside it without any problem.

Yes, it's fine if you only use layzgit/vifm/nnn/ranger... integration. But if you want to use [floaterm](https://github.com/voldikss/vim-floaterm#floaterm) or [git](https://github.com/voldikss/vim-floaterm#git) integration, `nvr` must be installed.

**Comment by smartding** [comment]
OK, got it
