### ISSUE TITLE
Using FloatermSend sends wrong indentations for functions in iPython

### ISSUE THREAD

**Issue by a-elhag** [voldikss/vim-floaterm#150]
If I open a floaterm terminal and open up a **python shell**, and send the following 3 lines of code using ```:FloatermSend```. Everything works as expected. 

```
for i in range(2):
    print(i)
    print(i)
```

But if I do the same thing with an **ipython shell** using ```:FloatermSend```, you get an indentation error because it is sent to iPython like this:

```
In [1]: for i in range(2):
   ...:         print(i)
   ...:             print(i)
 
```

**Comment by voldikss** [comment]
This plugin is a common use plugin, that is to say it only providers simple functionalities for features like REPL. 

To archieve better experience, you should use those plugins designed specifically for REPL.

**Comment by voldikss** [comment]
Also see #86

**Comment by voldikss** [comment]
There is one feature lost in this plugin: use `:FloatermSend` for **virtical visual selection**. So I labelled this issue as `enhancement` and will implement it when I have spare time.

**Comment by a-elhag** [comment]
Thanks! Also, the issue happens when you use %FloatermSend too. It's not only for vertical visual selection.

**Comment by voldikss** [comment]
> Thanks! Also, the issue happens when you use %FloatermSend too. It's not only for vertical visual selection.

Yes, `%FloatermSend` means sending the whole buffer(certainly contains those prefix strings like `In [1]:`). After the feature implemented, you can virtically select only
```python
for i in range(2):
    print(i)
    print(i)
```
. Then when you use `:'<,'>FloatermSend`, it will send the text you just selected.

**Comment by voldikss** [comment]
Sorry I've found that I totally misunderstood your problem. Yes, it is a bug, and I'll try to fix it.

**Comment by voldikss** [comment]
It is a problem caused by Ipython's autoindent feature.

I prefer not to detect ipython and make some patches inside the plugin(for there is not a elegant way to archive that). But the better solution seems to disable Ipython's autoindent when using this plugin.

According the official [documentation](https://ipython.org/ipython-doc/3/interactive/reference.html#autoindent), 
> Autoindent is ON by default, but it can cause problems with the pasting of multi-line indented code (the pasted code gets re-indented on each line). A magic function %autoindent allows you to toggle it on/off at runtime. You can also disable it permanently on in your ipython_config.py file (set TerminalInteractiveShell.autoindent=False).
>
> If you want to paste multiple lines in the terminal, it is recommended that you use %paste.

there is two methods to disable it:

- Disable it temporarily using `%autoindent`
- Disable it persistently throught modifing `ipython_config.py`(see [here](https://ipython.org/ipython-doc/3/config/intro.html) for the infomation about that file)

Hope it help. If there are other problems, feel free to comment/reopen this issue.

**Comment by a-elhag** [comment]
Thanks, this fixes the problem for me perfectly. And you can also remove autoindent by running ipython like this from the command line:

```ipython --no-autoindent```
