### ISSUE TITLE
how to enable scroll by key jk in floaterm when process exited

### ISSUE THREAD

**Issue by windwp** [voldikss/vim-floaterm#160]
### Describe the bug
open vim run command 
:FloatermNew --autoclose=0 cat ~/.vimrc
i want to use jk to scroll in it
Thank

**Comment by voldikss** [comment]
Firstly you should go back to the NORMAL mode using <C-\><C-n>

**Comment by windwp** [comment]
sorry for that question but
how can i do this automatic by script
call feedkeys("<c-\\><c-n>")
i use this but it not work.
Thank

**Comment by voldikss** [comment]
> @voldikss
> sorry for that question but
> how can i do this automatic by script
> call feedkeys("<c-\>")
> i use this but it not work.
> Thank

Actually I don't know either. I've also tried that but `autocmd` didn't work.

It seems this was caused by inside the plugin, since I've used `startinsert` for every floaterm.

If you think this feature is much necessary, feel free to reopen the issue and I'll add an argument `--autoinsert=0` to the command `:FloatermNew` to solve it.

**Comment by voldikss** [comment]
Reopened this issue and it will be implemented in the branch https://github.com/voldikss/vim-floaterm/tree/more-args-for-FloatermNew

**Comment by windwp** [comment]
hi i use script after call floatermnew and it work
``` vim  
stopinsert 
```
