### ISSUE TITLE
Hide/unhide (toggle) without moving focus?

### ISSUE THREAD

**Issue by mitchellwrosen** [voldikss/vim-floaterm#163]
Hi there, is it possible to toggle a hidden floaterm, but not bring focus to it? Thanks :)

**Comment by voldikss** [comment]
Not possible for now. But I planned to add an argument `--autofocus` for `:FloatermNew` and `:FloatermToggle`. After that this can be archived using `--autofocus=0`.

**Comment by voldikss** [comment]
Sorry but I decide not to add this feature after trying to implement it. Because it will break the behavior of `:FloatermToggle`: If we run `:FloatermToggle` after `:FloatermNew --nofocus`, should we close that floaterm or just jump into it? And the next time when we toggle back that floaterm, should it still be focused or we just nofocus at the first time it is spawned?

In many cases, this functionality can be achieved by creating another function wrapping `:FloatermNew` or `:FloatermToggle`. For example

```vim
command! FloatermToggleNofocus call FloatermToggleNofocus()
function! FloatermToggleNofocus() abort
  if len(filter(tabpagebuflist(), { _,b -> getbufvar(b, '&ft') == 'floaterm' })) >= 1
    FloatermHide!
    return
  endif
  FloatermToggle
  stopinsert
  wincmd p
endfunction
```
