### ISSUE TITLE
Use native (nvr) --remote options to open files

### ISSUE THREAD

**Issue by adigitoleo** [voldikss/vim-floaterm#184]
I started to have a look at improving `bin/floaterm` to deal with a few issues, but then I realised: do we really need this wrapper? I already use `nvr` often to open files when I am in a different terminal window, and I think vim users will probably have aliases for `vim --remote`. It would be nice if these same aliases could work from the floaterm, instead of only `floaterm $file`.

I don't know how hard it is to implement, but it seems like it should be possible: `nvr $file` already works from neovim's `:terminal`. I tried the same command inside a floaterm, but the file stays in the floating terminal instance (although the window borders dissappear and the floaterm file type is lost). I think this is a bigger change, so I want to ask what people think before starting work on this.

At the moment, launching a floaterm involves two steps (I think):
- Construct the floating window (`autoload/floaterm/window.vim`)
- Create a new terminal buffer in that window (`autoload/floaterm/terminal.vim`)

So, we will need to make any non-terminal buffers that end up in the floating window be pushed to the "main" (neo)vim window instead. Something like an automatic version of:

```
nvr $file
:q 
:b # 
```

Benefits of this approach:
- Ability to open multiple files (at the moment, `bin/floaterm` only passes `$1` file)
- Ability to use all of the `nvr` or `vim --remote` options, like passing commands to be run after opening via `-cc 'command'`, which would also resolve #161 (and #179, we don't need to change $PATH anymore)
- Consistency with opening files from `:terminal` buffers
- No need for shell scripts, also `floaterm#util#edit` could be removed

**Comment by voldikss** [comment]
Thanks for this nice proposal!

However, it still worths some time to look deeply into the implementation.

Sadly I don't have much spare time in several months. So let it stay here until I am free.

**Comment by adigitoleo** [comment]
Just leaving this here for reference. It might be necessary to change some of the popup implementation to achieve this, and https://github.com/junegunn/fzf/commit/7ceb58b2aadfcf0f5e99da83626cf88d282159b2# is interesting because it added popup support to fzf, which can open (multiple) files -- similar to what we want here.

**Comment by voldikss** [comment]
I've looked into that in fzf recently. However, there is another problem: nvr doesn't support vim8, so there seems no solutions but using a [floaterm script](https://github.com/voldikss/vim-floaterm/blob/master/bin/floaterm).

**Comment by voldikss** [comment]
And also that commit in fzf can not help solve this issue, even for nvim. `:FZF` starts from `termopen()` with a callback function registered, (see [this](https://github.com/junegunn/fzf/blob/7ceb58b2aadfcf0f5e99da83626cf88d282159b2/plugin/fzf.vim#L747)). So when user hit a candidate, the job exits and the callback function will close the floating window and open the file selected in the normal window.

However, the case is different here. In the floaterm window, we can not have a onexit callback function for nvr because we are already in a sub shell-process. 

When we use `nvr somefile` the file will be opened in the floaterm which means the original buffer got wipeout. So I created the following autocmd once floaterm is opened,

```vim
autocmd BufWipeout <buffer> hide
```

I originally thought that if we type `nvr somefile`, the floating window would be closed so that the `somefile` buffer would be leaved to a normal window. But sadly it didn't work.

There must not be a good enough solution for this issue and #179 and also #161. But still thank you for the proposal.

**Comment by adigitoleo** [comment]
That makes sense, I think I came to similar roadblocks when I was messing around a few months ago. For now it's probably best to just tweak the script where possible and wait for native popup terminal and job control features to improve.

Thanks for looking into this.
