### ISSUE TITLE
opening windows on non-floating position is broken

### ISSUE THREAD

**Issue by wookayin** [voldikss/vim-floaterm#189]
# Describe the bug

Your API got broken again :):):)

### To Reproduce

```
call floaterm#new(1, "ls", {'position':'right'}, {})
```

The window should open in the right side as a vsplit window, but a floating window is opened.

### Enviroment
 - floaterm f2506e480c1d6bf91c94465b01aab228dca9262f
 - neovim 0.4.2, 0.5.0 nightly

**Comment by voldikss** [comment]
Sorry for that but I've removed the API part in the documentation. I'm not good at code design so I have to change those functions from time to time instead of making a fixed and best structure. In consideration of that, those functions were not be public anymore and I am not able to be responsible for the break cases caused by using those functions.

**Comment by voldikss** [comment]
Please use `call floaterm#new(1, "ls", {'position':'right'}, {})` instead, even though I couldn't guarantee it validity in a long time.

**Comment by wookayin** [comment]
It was public. I will catch up the api changes accordingly.
