### ISSUE TITLE
Is it possible to pass the --autoclose flag to asynctasks.vim?

### ISSUE THREAD

**Issue by eulertour** [voldikss/vim-floaterm#198]
As the title says, I'd like to pass the --autoclose flag to certain tasks, e.g. with
```
[test]
command=pytest
output=terminal
autoclose=1
```

**Comment by voldikss** [comment]
Sorry but this is not possible in `.tasks` file. As asynctasks.vim doesn't support that keyword.

But if you want, you can rewrite your own function instead of using the code provided [here](https://github.com/voldikss/vim-floaterm#asynctasksvim) to implement this feature. You may need some functions such as [`floaterm#new()`](https://github.com/voldikss/vim-floaterm/blob/f6654e2f9c29bd85039a11f305acd4e5222b03f8/autoload/floaterm.vim#L55) and others
