### ISSUE TITLE
Question: automatically select the current file when calling lf wrapper

### ISSUE THREAD

**Issue by noib3** [voldikss/vim-floaterm#209]
I've been trying to find a way to automatically select the current file after calling lf via `:FloatermNew lf`. I tried the following
```vim
nmap <silent> ll :FloatermNew lf <bar>
                  \ execute '!lf -remote "send $id select ' . % . '"<CR>'
```
but it doesn't seem to work, the terminal window closes immediately. Is it possible to do that?

**Comment by weilbith** [comment]
Well, your command gets executed and thats it. I think you should try to first just open the terminal and then make use of the `FoatermSend` command.

**Comment by voldikss** [comment]
Hi @noib3 

I am not familiar with `lf` but after a quick skim of its man page I can confirm that the mapping above won't take effect. Reasons:

1. You can not use `<bar>` in the `FloatermNew` command because it seeks to have the consistent behavior with builtin `:termiinal` command which doesn't support `<bar>`(It sees the `bar` as an argument. `:help :bar` to get more info about it.). Therefore, I recommended you separating it to 2 commands wrapped into one function which can be used to define a mapping.

2. Actually you can not aquire `$id` in the shell commands `!lf ...` since `lf` was spawned in some place like a child process. The I recommend sending it without a specific `$id` which means this will be executed in all the lf clients(Though it will cause some unexpected behavior if you have multiple lf clients opened...).

`FloatermSend` won't help because the terminal spawns `lf` is at the `Canonical` mode so that lf won't handle that command. However still thanks @weilbith for the response.

**Comment by noib3** [comment]
Hi @voldikss, thanks for your reply. I tried separating the commands and putting them into a function like you suggested, but it doesn't seem to work.

This is what I have
```vim
nmap <silent> ll :call <SID>open_lf_select_current_file()<CR>

function! s:open_lf_select_current_file()
  execute "FloatermNew lf"
  silent execute '!lf -remote "send select ' . expand("%:p") . '"'
endfunction
```
the floating terminal opens correctly, but the second line of the function (`silent execute...`) seems to be ignored. Any ideas?

**Comment by voldikss** [comment]
1. What you get from `expand("%:p")` is not the current file name, because when you call this function the cursor has been in the floaterm window. So you have to get and store the current filename.
2. There is a delay between executing script and opening `lf`. Therefore, if you send that command right now after `FloatermNew lf` the command it has no effects.

The following code works for me but as what I've mention in the second point, it has a delay. So the best solution is to use `timer_start`function. But unluckily, the delay was a little large, over 500ms...
```vim
nmap <silent> ll :call <SID>open_lf_select_current_file()<CR>

function! s:select(filename, ...) abort
  silent execute printf('!lf -remote "send select %s"', a:filename)
endfunction

function! s:open_lf_select_current_file()
  let filename = expand('%')
  execute "FloatermNew lf"
  call timer_start(500, function('s:select', [filename]), {'repeat': 3})
endfunction
```

**Comment by noib3** [comment]
Thanks, that works perfectly. I managed to get the delay down to 100ms, which seems to work just fine.
