### ISSUE TITLE
[Feature Request] Floaterm Restore on Session Restore

### ISSUE THREAD

**Issue by TheCedarPrince** [voldikss/vim-floaterm#213]
Hi @voldikss - thanks for the wonderful tool! I use it everyday. In fact, that is why I am opening this issue. :)

I make extensive use of sessions while working with (neo)vim and I also use floaterms significantly. Would it be possible to add the capability of saving floaterm information to a session file such that floaterms, with specific execution commands, would automatically start up upon session restore? This is similar to #191 and it partially implements my idea but it would be great to have this functionality be customized to a session by session basis.

Let me know if you have any questions or if this is outside the scope of the project! Thank you!

**Comment by voldikss** [comment]
Hi @TheCedarPrince, in my personal opinion terminal session is useless: it can not save your running job which could be the only thing we want to store. Actually there are no quite demand to do that because we can easily open a floaterm.

Besides, I am quite not familiar with how to save and restore sessions. Though I sometimes use session command provided by coc.nvim.

I am going to close this issue but if you have any thoughts feel free to comment. I'll consider it in the future if I have free time and find it useful.

**Comment by TheCedarPrince** [comment]
Hey @voldikss - that's reasonable. My use case may be somewhat niche as my setup is as follows:

I use tmux to start a workspace. From there, I create my windows and set-up just the way I want them in tmux. I utilize [tmux-resurrect](https://github.com/tmux-plugins/tmux-resurrect) and [tmux-continuum](https://github.com/tmux-plugins/tmux-continuum) to save and reload my window layouts and use [vim-obsession](https://github.com/tpope/vim-obsession) to also have tmux-resurrect automatically reload my vim sessions upon reboot of the tmux session. So for me, vim sessions are invaluable as I don't have to worry about my workspace ever as it will persist from each work period to work period regardless of whether I have to shut down my computer.

My setup looks like this:

![image](https://user-images.githubusercontent.com/29561456/100644199-01a14300-3309-11eb-9bfd-07e593418773.png)
