### ISSUE TITLE
Floaterm window title number info missing in wintype normal mode

### ISSUE THREAD

**Issue by shivanju** [voldikss/vim-floaterm#224]
It seems that currently there is no way to tell on what instance of floaterm I am just by looking at it. In floating mode this can be seen in title of the floating window.

**Comment by voldikss** [comment]
Hmm yes, but split(normal) window doesn't (and can not) have a border. So no places to put a title.

Though I have considered making them in the statusline, but not a good thing.

**Comment by ekickx** [comment]
Can we get the value of g:

**Comment by ekickx** [comment]
Can

**Comment by ekickx** [comment]
Can we get the value of `g:floaterm_title`'s `$1` and `$2`? So user can make their number info in statusline. I tried in galaxyline and the result is like this.
![image](https://user-images.githubusercontent.com/26477782/103743194-6fd6d500-502e-11eb-819f-037ad1cfdafd.png)

**Comment by voldikss** [comment]
@ekickx You can not because the `$1` and `$2` are calculated util when rendering border. 

Here is the code used for the `current index` and `floaterm count`: https://github.com/voldikss/vim-floaterm/blob/master/autoload/floaterm/window.vim#L31-L39

So if you want, you can call `len(floaterm#buflist#gather())` to get the total number of the floaterms, call `index(buffers, a:bufnr) + 1` to get the current floaterm index. 

Here is a lightline exmaple,

```vim
let g:lightline = {
  \ 'colorscheme': 'aurora',
  \ 'active': {
    \ 'right': [
      \ ['floaterm_info']
    \ ]
  \ },
  \ 'component_function': {
    \ 'floaterm_info': 'Lightline_FloatermInfo',
    \ ....
  \ },
\ }

function! Lightline_FloatermInfo() abort
  let buffers = floaterm#buflist#gather()
  let cnt = len(buffers)
  let cur = floaterm#buflist#curr()
  let idx = index(buffers, cur) + 1
  return printf('floaterm %s/%s', idx, cnt)
endfunction
```

The above code could meet your needs.
![image](https://user-images.githubusercontent.com/20282795/103760734-80984280-5050-11eb-874c-fb8640751738.png)

**Comment by voldikss** [comment]
I was formerly thought maintaining two global variables so that users can easily use them in the statusline, but then I found it's ugly to do that so I quit.

If you real want to see floaterm info in the status line, the above code is workable enough.

**Comment by voldikss** [comment]
If you want to hide the info when there are no floaterms opened, change the function

```vim

function! Lightline_FloatermInfo() abort
  let buffers = floaterm#buflist#gather()
  let cnt = len(buffers)
  if cnt == 0 | return '' | endif
  let cur = floaterm#buflist#curr()
  let idx = index(buffers, cur) + 1
  return printf('floaterm %s/%s', idx, cnt)
endfunction
```

**Comment by ekickx** [comment]
Oh cool. Thanks for the answer.
