### ISSUE TITLE
Popup term in wrong location.

### ISSUE THREAD

**Issue by lkhphuc** [voldikss/vim-floaterm#24]
Hi, 
When I split vertically into 2 windows, and the cursor is on the 2nd window, on the right, my centered float term is no longer centered like this.
<img width="1680" alt="Screenshot 2020-01-12 at 15 31 32" src="https://user-images.githubusercontent.com/12573521/72221258-d5de6880-3550-11ea-8c04-b11918b8727b.png">

Could you possibly know why?
Thank you.

**Comment by wookayin** [comment]
Which commit/version of vim-floaterm are you using? I had experienced exactly the same issue, but after upgrade (e.g. 619602c as of 2019-12-31) it was fixed (shows correctly at the center).

**Comment by wookayin** [comment]
I am sorry, the latest 619602c still have the problem -- happens when floaterm was invoked on right windows. @voldikss seems to have a same mistake discussed in #10 (e524e7c0d) while implementing the border feature.

Changing two occurrences of (L260 and L294) `'relative': 'win'` to `relative': 'editor'` would fix the problem.

**Comment by voldikss** [comment]
Thanks @wookayin !

**Comment by lkhphuc** [comment]
Great, thank you all so much.
