### ISSUE TITLE
Feature request: FloatermBorderNC

### ISSUE THREAD

**Issue by Falkgaard** [voldikss/vim-floaterm#276]
### Describe your question, feature request, or bug.

Hi, there are Floaterm and FloatermNC highlight groups, but there doesn't appear to be a NC equivalent for FloatermBorder. Would this be possible to add? I think a dark border when inactive and a bright border when active is very helpful.

Love the plugin!

Best regards,
-Falkgaard

**Comment by voldikss** [comment]
> Would this be possible to add?

Sadly no.

Since the current implementation of the border is very tricky —— behind the floaterm window, there is another floating window which is used to render a border. Hence, the cursor will always be in the floaterm window while not the border window. Hence, the border highlight will always be `FloatermBorderNC` if there exists such option.

From what has been mentioned above, I tend to not add that option until neovim has its built-in floating border implementation.
