### ISSUE TITLE
Title is missing when win type is 'split|vsplit'.

### ISSUE THREAD

**Issue by Napoleon-Jm** [voldikss/vim-floaterm#340]
RT,

When win type is set to split or vsplit, the float title is missing to show, that will confused when multi floaterm window opened.

**Comment by adigitoleo** [comment]
In this situation, the title is printed to the usual location, i.e. the status bar. See screenshot. Yes, it looks a lot more ugly, but this is because there is currently no upstream support for custom terminal buffer naming/URI scheme: https://github.com/neovim/neovim/issues/3278

![image](https://user-images.githubusercontent.com/34595875/152625020-fdb15759-b73d-4aa3-9c99-cd42951fe7d4.png)

**Comment by voldikss** [comment]
@adigitoleo is right, thanks for the explaination.
