### ISSUE TITLE
Can it provide a variable like b:floaterm_opts, g:floterm_opts?

### ISSUE THREAD

**Issue by Freed-Wu** [voldikss/vim-floaterm#89]
such as
```
let b:floaterm_opts={
'term_finish': 'close',
'curwin': 1,
}
```

so that user can define terminal.

thanks!

**Comment by voldikss** [comment]
Hi @Freed-Wu,

There are two kinds of opts used when opening a floaterm: `win_opts` & `job_opts`.

- `win_opts` can be specified using command(`:FloatermNew/Toggle`) arguments.
- `job_opts` must not be modified or defined by users. For example, here `'term_finish'` must be `'close'`, otherwise this will lead to some stange behaviors.

Hmmmm, so I do not incline to implement this.

**Comment by voldikss** [comment]
I've made some changes. Now you can open a floaterm with specified opts. e.g.
```vim
let floaterm_job_opts={
'term_finish': 'close',
'curwin': 1,
}
call floaterm#new(&shell, {}, floaterm_job_opts)
```

**Comment by vn-ki** [comment]
Does this mean `floaterm#new` can be considered public API and won't break as often?

**Comment by voldikss** [comment]
@vn-ki yes

**Comment by wookayin** [comment]
But it was broken in this commit :) I wish `floaterm#new()` itself (as previous) would run with the default options for `winopts` and `jobopts` (and `cmd=""`).

**Comment by voldikss** [comment]
> But it was broken in this commit 

Sorry can you be more specific?

**Comment by Freed-Wu** [comment]
```
call floaterm#new(&shell, {}, {'curwin':1}, &shell)
```
will open two windows, not open window in current window, why?
